{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pose-estimation-s3-latest-image.serviceAccountName" . }}
  labels:
{{ include "pose-estimation-s3-latest-image.labels" . | nindent 4 }}
{{- end -}}
